version: "3.9"

services:

# =================BACKEND=SERVICE========================
  backend:
    build:
      context: ./nekki-api
      dockerfile: Dockerfile
    container_name: API
    env_file:
      - .env
    ports:
      - 8000:8000
    networks:
      - nekki-network
    user: python
    volumes:
      - ./nekki-api:/opt/python


  # =================FRONTEND=SERVICE=====================
  frontend:
    build:
      context: ./nekki-front
      dockerfile: Dockerfile
    container_name: FE
    depends_on:
      - backend
    command: npm run dev
    environment:
      - CHOKIDAR_USEPOLLING=true
    stdin_open: true
    tty: true
    user: node
    env_file:
      - .env
    ports:
      - 3000:3000
    networks:
      - nekki-network
    volumes:
      - ./nekki-front:/opt/node
      - '/opt/node/node_modules'

  # =================NGINX=SERVICE=======================
  nginx:
    image: nginx:1-alpine
    container_name: nginx
    depends_on:
      - frontend
    ports:
      - 80:80
    networks:
      - nekki-network
    restart: always
    volumes:
      - ./conf/default.conf:/etc/nginx/conf.d/default.conf

# ====================NETWORKS==========================
networks:
  nekki-network:
    driver: bridge